config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
   authenticated :user do
    root "categories#index", as: :authenticated_root
  end

  unauthenticated do
    root "splash_screen#index", as: :unauthenticated_root
  end
 
resources :categories do
  resources :transactions
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :transaction_categories
  has_many :transactions
  has_many :related_transactions, through: :transaction_categories, source: :related_transaction

  validates :name, presence: true
  validates :icon, presence: true

  def total_amount
    total = 0
    transactions.each do |transaction|
      total += transaction.amount.to_i
    end
    total
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'author_id'
  has_many :transaction_categories
  has_many :categories, through: :transaction_categories

  validates :name, presence: true, length: { maximum: 255 }
  validates :amount, presence: true, numericality: { greater_than: 0, only_integer: true }
end

app/models/transaction_category.rb
class TransactionCategory < ApplicationRecord
  belongs_to :related_transaction, class_name: 'Transaction', foreign_key: 'transaction_id'
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :transactions, class_name: 'Transaction', foreign_key: 'author_id'
  has_many :categories, class_name: 'Category', foreign_key: 'author_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  def index
    @categories = Category.where(author: current_user)
  end

  def new
    @category = current_user.categories.build
  end

  def create
    @category = current_user.categories.new(category_params)

    if @category.save
      redirect_to categories_path, notice: 'Category was successfully saved.'
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/splash_screen_controller.rb
class SplashScreenController < ApplicationController
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @category = Category.find(params[:category_id])
    @transactions = @category.transactions.where(author_id: current_user.id).order(created_at: :desc)
  end

  def new
    @category = Category.find(params[:category_id])
    @transaction = Transaction.new
  end

  def create
    @transaction = current_user.transactions.new(transaction_params)
    @transaction.user_id = current_user.id
    if @transaction.save
      redirect_to category_transactions_path(transaction_params[:category_id]),
                  notice: 'Transaction was successfully saved.'
    else
      render :new
    end
  end

  private

  def transaction_params
    params.require(:transaction).permit(:name, :amount, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/splash_screen_helper.rb
module SplashScreenHelper
end

app/views/categories/index.html.erb
<div class="container">
  <h1 class="page-name">Categories</h1> <div class="log-out">
 <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "log-out" %>
</div>
</div>

<div class="categories">
  <% @categories.each do |category| %>
    <a href="<%= category_transactions_path(category) %>" class="category-link">
      <div class="category-container">
        <div class="category-img">
          <img class="category-image" src="<%= category.icon %>" alt="<%= category.name %>_image">
        <p class="category-name"><%= category.name %></p>
         </div>
      <p class="category-amount">$<%= category.total_amount %></p>
       </div>
       <br>
    </a>
  <% end %>
</div>

<a class="add-category" href="<%= new_category_path %>">
  <button class="btn-add-category">Add a New Category</button>
</a>

app/views/categories/new.html.erb
<div class="category-header">
  <a class="back-button" href="<%= categories_path %>">
    <img class="back-icon" src="<%= asset_path('back-white.png') %>" alt="back-icon">
  </a>
  <h1 class="add-name">Add a New Category</h1>
  </div>


<%= form_with(model: @category, url: categories_path) do |form| %>
  <div class="category-form">
    <div class="form-field">
      <%= form.text_field :name, autofocus: true, autocomplete: "name", placeholder: "Category", class: "form-input", required: true %>
    </div>

    <div class="form-field">
      <%= form.text_field :icon, autofocus:true, autocomplete: "icon", placeholder: "Icon URL", class: "form-input", required: true %>
    </div>

    <div class="form-btnr">
      <%= form.submit 'Save', class: "btn-save" %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/splash_screen/index.html.erb
<div class="splash-container">
  <h1 class="app-name">Budget App</h1>

  <div class="splash">
    <%= link_to 'LOG IN', new_user_session_path, class: 'log-btn' %>
     <%= link_to 'SIGN UP', new_user_registration_path, class: 'sign-btn' %>
  </div>
</div>

app/views/transactions/index.html.erb
<div class="category-header">
  <a class="back-btn-a" href="<%= categories_path(@category) %>">
      <img class="back-icon" src="<%= asset_path('back-white.png') %>" alt="back-icon">
  </a>
  <h1 class="add-name">Transactions</h1>
</div>

  <div class="category-containerr">
   <div class="category-img">
          <img class="category-image" src="<%= @category.icon %>" alt="<%= @category.name %>_image">
        <p class="category-name"><%= @category.name %></p>
        </div>
      <p class="category-amount">$<%= @category.total_amount %></p>
      </div>

<div class="transactions">
    <% @transactions.each do |transaction| %>
      <div class="transaction">
        <p class="transaction-name"><%= transaction.name %></p>
        <p class="transaction-amount">$<%= transaction.amount %></p> 
      </div>
      <br>
    <% end %>
    </div>

  <a class="add-transaction-a" href="<%= new_category_transaction_path(@category) %>">
    <button class="add-transaction-btn">Add a New Transaction</button>
  </a>
</div>

app/views/transactions/new.html.erb
<div class="category-header">
  <a class="back-button" href="<%= category_transactions_path(@category) %>">
    <img class="back-icon" src="<%= asset_path('back-white.png') %>" alt="Back">
  </a>
  <h1 class="add-name">Add a New Transaction</h1>
</div>

<%= form_with(model: [@category, @transaction], url: category_transactions_path(@category)) do |form| %>
  <div class="transaction-form-container">
    <div class="form-field">
      <%= form.text_field :name, autofocus: true, autocomplete: "name", placeholder: "Transaction Name", class: "form-input", required: true %>
    </div>

    <div class="form-field">
      <%= form.number_field :amount, autocomplete: "amount", placeholder: "Amount", class: "form-input", required: true %>
    </div>

    <div class="select">
     <%= form.collection_select :category_id, Category.where(author: current_user).all, :id, :name, prompt: 'Select a Category', class: "select" %>
    </div>

    <div class="form-btn-container">
      <%= form.submit 'Save', class: "btn-save" %>
    </div>
  </div>
<% end %>